#!/bin/sh
#
# LBS daemon starter script.
# You should not call tis script directly. Use the "lbs" init script instead.
#
BASE=/tftpboot/revoboot

mypidof()
{
        if `which pidof >/dev/null 2>&1`; then
                pidof "$@"
        else
                ps ax | grep "$@" | grep -v grep | awk '{print $1}'
        fi
}


LBSPID=$(mypidof getClientResponse)
if [ -n "$LBSPID" ]; then
	echo " A process ($LBSPID) is already running." >&2
	exit 1
fi

$BASE/bin/getClientResponse >/dev/null 2>&1 &

sleep 1

LBSPID=$(mypidof getClientResponse)
test -z "$LBSPID" && { echo " FAILED" >&2 ; exit 0 ;}
echo $LBSPID > /var/run/lbs.pid
echo -en "\tOK (daemon)"

if [ -x /usr/share/webmin/lbs/wshaper ] 
then
    /usr/share/webmin/lbs/wshaper start
    echo -n " (traffic shaping)"
fi
echo
