#!/bin/sh

# Get the uid of the new user
VALUE=`cat $1 | grep ^uid: | sed "s/uid: //"`
PASSWD=`cat $1 | grep ^userPassword: | sed "s/userPassword: //"`

echo "$1" > "tmp/samba_add_attr_$VALUE$PASSWD"

exit 0
