Pulse - Core: MMCBaseTransport Class Reference
MMCBaseTransport Class Reference
Inherits object.
Inherited by MMCSafeTransport, and MMCTransport.
Public Member Functions
def __init__ (self, username, passwd, use_datetime=0)
def send_basic_auth (self, connection)
def send_cookie_auth (self, connection)
def send_host (self, connection, host)
override the send_host hook to also send authentication info
Detailed Description
Standard synchronous Transport for the MMC agent.
MMC agent provides a slightly modified XMLRPC interface.
Each xmlrpc request has to contains a modified header containing a
valid session ID and authentication information.
Definition at line 72 of file sync.py.
Constructor & Destructor Documentation
def __init__ (self, username, passwd, use_datetime = 0)
This method returns an XMLRPC client which supports
basic authentication through cookies.
Definition at line 82 of file sync.py.
References MMCBaseTransport._connection_requires_compat(), MMCBaseTransport._make_connection_compat(), MMCBaseTransport._use_datetime, MMCBaseTransport.accept_gzip_encoding, MMCBaseTransport.credentials, and MMCBaseTransport.make_connection.
Member Function Documentation
def send_basic_auth (self, connection)
Include HTTPS Basic Authentication data in a header
Definition at line 118 of file sync.py.
References MMCBaseTransport.credentials.
Referenced by MMCBaseTransport.send_host().
def send_cookie_auth (self, connection)
Include Cookie Authentication data in a header
Definition at line 125 of file sync.py.
Referenced by MMCBaseTransport.send_host().
def send_host (self, connection, host)
override the send_host hook to also send authentication info
This method override the send_host method of SafeTransport to send
authentication and cookie info.
Definition at line 142 of file sync.py.
References MMCBaseTransport.credentials, MMCBaseTransport.make_connection, MMCBaseTransport.parse_response(), MMCBaseTransport.send_basic_auth(), MMCBaseTransport.send_cookie_auth(), MMCBaseTransport.send_host(), and MMCBaseTransport.verbose.
Referenced by MMCBaseTransport.send_host().
The documentation for this class was generated from the following file:
agent/mmc/client/sync.py