Pulse - Core: PluginConfigFactory Class Reference
PluginConfigFactory Class Reference
Inherits object.
Static Public Member Functions
def new (cls, name, args, kwargs)
def get (name)
Detailed Description
For each plugin, we need to have only ONE config instance.
This is useful, for example so that the Admin-Configuration plugin
can change the config at run time, and every classes using the a PluginConfig will get the new values without restarting.
So, every PluginConfig (or a derivated) instance should be created this way
Definition at line 154 of file config.py.
Member Function Documentation
get()
def get (name) static
Returns the PluginConfig instance that was
created with this name.
If it doesn't exist, raise an error because that should never
happen.
Definition at line 174 of file config.py.
Referenced by MMCConfigParser.getdn(), MMCConfigParser.getpassword(), PPolicyConfig.readConf(), PluginConfig.readConf(), LDAPConnectionConfig.readLDAPConf(), SubscriptionConfig.readSubscriptionConf(), and MMCConfigParser.safe_get().
new()
def new (cls, name, args, kwargs) static
If no instance of a class (with this name) has not already
been created, create it and keep it in the dict.
If one already exist, just return it.
Definition at line 163 of file config.py.
The documentation for this class was generated from the following file:
agent/mmc/support/config.py