Pulse - Core: AbstractTpl Class Reference
AbstractTpl Class Reference
Public Member Functions
display ($arrParam=array())
displayRo ($arrParam)
Detailed Description
astract class template
Definition at line 51 of file FormGenerator.php.
Member Function Documentation
display()
display ($arrParam = array())
display abstract Element $arrParam accept ["value"]
Definition at line 59 of file FormGenerator.php.
Referenced by displayRo().
displayRo()
displayRo ($arrParam)
Read Only display function
Definition at line 66 of file FormGenerator.php.
References display().
Referenced by CheckboxTpl\display(), FormElement\display(), and TrFormElement\display().
The documentation for this class was generated from the following file:
web/includes/FormGenerator.php