Pulse - Core: MMCApp Class Reference
MMCApp Class Reference
Public Member Functions
MMCApp ()
& getStyle ()
this function return uniq style object this is used to add CSS in an uniq part of the page instead of flooding fragmented css in whole page. styleobject id display at the end of the page.
addModule ($mod)
& getModules ()
return all modules list
& getModule ($modname)
return a specific module
render ()
process ()
Static Public Member Functions
static & getInstance ()
Detailed Description
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com (c) 2007-2008 Mandriva, http://www.mandriva.com
$Id$
This file is part of Mandriva Management Console (MMC).
MMC is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
MMC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with MMC; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA Singleton objet, register all main mmc data
Definition at line 28 of file ModulesGenerator.php.
Member Function Documentation
addModule ($mod)
add a module into MMCApp
Parameters
mod Module Object to add
Definition at line 72 of file ModulesGenerator.php.
static& getInstance () static
getInstance (return uniq object) fake static element (due to php4 bad object integration) with a global value
Definition at line 47 of file ModulesGenerator.php.
References MMCApp().
Referenced by StyleGenerator\render().
& getModule ($modname)
return a specific module
Parameters
$modname name
Returns
Module Object
Warning
if Module name do not exist... unknown value is return
Definition at line 92 of file ModulesGenerator.php.
& getModules ()
return all modules list
Returns
an associeted array like 'base' => 'base object', 'samba'=> 'samba object'
Definition at line 82 of file ModulesGenerator.php.
Referenced by process().
& getStyle ()
this function return uniq style object this is used to add CSS in an uniq part of the page instead of flooding fragmented css in whole page. styleobject id display at the end of the page.
Returns
unique style object
Definition at line 64 of file ModulesGenerator.php.
MMCApp ()
Constructor private
Definition at line 37 of file ModulesGenerator.php.
Referenced by getInstance().
process ()
This function process all Modules Create old array for retro compatibility etc...
Definition at line 107 of file ModulesGenerator.php.
References getModules().
Referenced by Module\getAPIVersion(), and StyleGenerator\render().
render ()
function called at very end of each page (css creation, etc...)
Definition at line 99 of file ModulesGenerator.php.
The documentation for this class was generated from the following file:
web/includes/ModulesGenerator.php