Pulse - Core: PluginManager Class Reference
PluginManager Class Reference
Inherits Singleton.
Public Member Functions
def isEnabled (self, plugin)
def getEnabledPlugins (self)
def getEnabledPluginNames (self)
def getAvailablePlugins (self)
def loadPlugin (self, name, force=False)
def startPlugin (self, name)
def loadPlugins (self)
def stopPlugin (self, name)
Detailed Description
This singleton class imports available MMC plugins, activates them, and
keeps track of all enabled plugins.
Definition at line 828 of file agent.py.
Member Function Documentation
getAvailablePlugins()
def getAvailablePlugins (self)
Fetch all available MMC plugin
@return: list of all mmc plugins names
@rtype: list
Definition at line 864 of file agent.py.
References PluginManager.pluginDirectory.
Referenced by PluginManager.loadPlugins().
getEnabledPluginNames()
def getEnabledPluginNames (self)
@rtype: list
@return: the names of the enabled plugins
Definition at line 857 of file agent.py.
References PluginManager.getEnabledPlugins().
Referenced by PluginManager.startPlugin().
getEnabledPlugins()
def getEnabledPlugins (self)
@rtype: dict
@return: the enabled plugins as a dict, key is the plugin name, value
 is the python module object
Definition at line 849 of file agent.py.
References PluginManager.plugins.
Referenced by PluginManager.getEnabledPluginNames().
isEnabled()
def isEnabled (self, plugin)
@rtype: bool
@return: Return True if the plugin has been enabled
Definition at line 842 of file agent.py.
References PluginManager.plugins.
Referenced by PluginManager.loadPlugins().
loadPlugin()
def loadPlugin (self, name, force = False)
Load a plugin with the given name.
To start one single module after the agent startup, use startPlugin()
instead
@returns: 4 on fatal error (mmc agent should not start without that
plugin), 0 on non-fatal failure, and the module itself if
the load was successful
Definition at line 878 of file agent.py.
Referenced by PluginManager.loadPlugins(), and PluginManager.startPlugin().
loadPlugins()
def loadPlugins (self)
Find and load available MMC plugins
@rtype: int
@returns: exit code > 0 on error
Definition at line 961 of file agent.py.
References PluginManager.getAvailablePlugins(), PluginManager.isEnabled(), PluginManager.loadPlugin(), and PluginManager.plugins.
startPlugin()
def startPlugin (self, name)
Force a plugin load.
Even if the configuration indicates the plugin is disabled,
we load it and add it to the loaded list.
Use it to start a plugin after the mmc agent startup, dynamically.
This tries to call the activateForced method of the plugin (for example to
ignore the disable = 1 configuration option)
Definition at line 937 of file agent.py.
References PluginManager.getEnabledPluginNames(), PluginManager.loadPlugin(), and PluginManager.plugins.
stopPlugin()
def stopPlugin (self, name)
Stops a plugin.
@rtype: boolean
returns: True on success, False if the module is not loaded.
Definition at line 1018 of file agent.py.
References PluginManager.plugins.
The documentation for this class was generated from the following file:
agent/mmc/agent.py