Pulse - Core: LogView Class Reference
LogView Class Reference
Public Member Functions
def revReadlines (self, arg, bufsize=8192)
def getLog (self, filter="")
Detailed Description
LogView class. Provide accessor to show log content
Definition at line 2623 of file __init__.py.
Member Function Documentation
getLog()
def getLog (self, filter = "")
Parse the log lines containing the filter string and matching the given patterns.
Try to return a list containing self.maxElt
Definition at line 2666 of file __init__.py.
References LogView.logfile, LogView.maxElt, LogView.parseLine(), LogView.pattern, and LogView.revReadlines().
Referenced by LogView.revReadlines().
revReadlines()
def revReadlines (self, arg, bufsize = 8192)
Reversed readlines
Taken from http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/496941/index_txt
Definition at line 2646 of file __init__.py.
References LogView.getLog().
Referenced by LogView.getLog().
The documentation for this class was generated from the following file:
agent/mmc/plugins/base/__init__.py