.TH MMC-STATS 1
.SH NAME
mmc-stats \- analyse mmc-agent log files
.SH SYNOPSIS
.B mmc-stats
.RI [ LOG ]
.SH DESCRIPTION
mmc-stats analyses a mmc-agent log file in DEBUG mode and displays some stats.
.SH OPTIONS
.TP
.B LOG
The path to the mmc-agent DEBUG log file
.SH AUTHOR
mmc-stats was written by Mandriva
.SH COPYRIGHT
.TP
(c) 2011-2012 Mandriva, http://www.mandriva.com
.TP
MMC is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH SEE ALSO
.BR mmc-agent (1),
.BR mmc-helper (1),
.BR mmc-add-schema (1)
