ERROR_INVALIDE_FILENAME = 1
ERROR_INVALIDE_DIRNAME = 2
ERROR_IS_NOT_FILE = 3
ERROR_IS_NOT_DIRECTORY = 4
ERROR_CREATE_FILE = 5
ERROR_CREATE_DIRECTORY = 6
ERROR_NOT_EXIST_FILE = 7
ERROR_NOT_EXIST_DIRECTORY = 8
ERROR_CAN_NOT_REMOVE_FILE = 9
ERROR_CAN_NOT_REMOVE_DIRECTORY = 10
ERROR_GET_ON_LOCAL_HOST = 11
ERROR_RENAME_FILE = 12
ERROR_REMOVE_FILE = 13
ERROR_PERMISSION = 14
ERROR_I_CAN_CHANGE_ATTRIBUTE_OF_FILE = 15
ERROR_DIRECTORY_NAME_IS_EMPTY = 16
ERROR_I_CAN_NOT_CREATE_DIRECTORY_IT_ALREADY_EXIST = 17
ERROR_I_CAN_NOT_REMOVE_DIRECTORY_IT_DO_NOT_EXIST = 18
ERROR_REMOVE_DIRECTORY = 19
ERROR_I_CAN_NOT_EXECUTE_FILE = 20
ERROR_FILE_TO_UPLOAD_NOT_EXIST = 21
ERROR_I_CAN_NOT_UPLOAD_FILE = 22
ERROR_CUSTOM = 42
ERROR_UNKOWN = 4242

errors = {
    'ERROR_INVALIDE_FILENAME':"err_invalide_filename",
    'ERROR_INVALIDE_DIRNAME':"err_invalide_dirname",
    'ERROR_IS_NOT_FILE':"err_isnt_file",
    'ERROR_IS_NOT_DIRECTORY':"err_isnt_dire",
    'ERROR_CREATE_FILE':"err_create_file",
    'ERROR_CREATE_DIRECTORY':"err_create_dir",
    'ERROR_NOT_EXIST_FILE':"err_not_exist_file",
    'ERROR_NOT_EXIST_DIRECTORY':"err_not_exist_dir",
    'ERROR_CAN_NOT_RM_FILE':"err_cant_rm_file",
    'ERROR_CAN_NOT_RM_DIR':"err_cant_rm_dir",
    'ERROR_PERMISSION':"err_perm",
    'ERROR_DEFAULT':"err_default"
}
