#!/usr/bin/python
# -*- coding: utf-8; -*-
#
# (c) 2010 Mandriva, http://www.mandriva.com
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2. If not, see <http://www.gnu.org/licenses/>.
#

"""
    This hook is called when a client asks to be authentifier.    
"""
import sys
import logging
hook = sys.argv[0]
mac = ""  # client MAC address
pwd = "" # client ID

if len(sys.argv) == 3:
    logging.info('HOOK %s : verify password' % hook)
else:
    logging.warning('HOOK %s : arg ' % hook)
    sys.exit(0)
mac = sys.argv[2]
pwd = sys.argv[1]
#fonction de verification du password menu
#fonction apres verification password
# envoi ok si verification bonne
sys.exit(0)
#envoi ko si verification mauvaise
#sys.exit(0)
