<?php
$templates = [
    "Win10-uefi" => "MountSystem
CopySysprep @@@filename@@@
CopyRunAtOnce
CopyAgent
CopyDrivers Windows10
",

"Win10-oem" => "MountSystem
CopySysprep @@@filename@@@
CopyRunAtOnce
CopyAgent
CopyDrivers Windows10
",

    "Win11-uefi" => "MountSystem
CopySysprep @@@filename@@@
CopyRunAtOnce
CopyAgent
CopyDrivers Windows11
",

    "Win11-oem" => "MountSystem
CopySysprep @@@filename@@@
CopyRunAtOnce
CopyAgent
CopyDrivers Windows11
",
    "Preseed" => "",
    "Bash" => '#!/bin/bash
# This script is generated by Medulla Mastering module
# If you are not sure about what this script does, do not modify it.

# setup for chroot
MountSystemLinux

CopyLinuxAgent

# Mount dest system
SetupChroot

# run the script in chroot
chroot /mnt/sda2 /bin/bash -c "$(cat /tmp/@@@filename@@@)
',
];

function get_template_integration($template){
    global $templates;
   
    if(isset($templates[$template])){
        return $templates[$template];
    }
    return "";
}