#!/bin/bash
ssh_pub_key="/opt/id_rsa.pub"


if [ -e ${ssh_pub_key} ]; then
    if ! [ -d "/root/.ssh" ]; then
	echo "Create missing SSH profile ..."   
        mkdir -p /root/.ssh
    fi 	
    	
    tee -a /root/.ssh/authorized_keys < ${ssh_pub_key}
    rm -f ${ssh_pub_key}
fi	


fusion_cfg="/etc/fusioninventory/agent.cfg" 
url=$(head -n 1 /opt/inventory.url)
if [ -n "$1" ]; then
    echo "INFO: Detected inventory url - $url"
else
    echo "ERROR: Unable to get inventory server URL"	    
    exit 1
fi 


if [ -f ${fusion_cfg} ];then
    grep -q "${url}" ${fusion_cfg} || echo "server = ${url}" >> ${fusion_cfg}
    rm -f /opt/inventory.url
else
    echo "ERROR: Unable to find fusioninventory config file"	
    exit 1
fi

echo "INFO: Running initial inventory"
/usr/bin/fusioninventory-agent

