.TH PULSE2-SCHEDULER-MANAGER 1
.SH NAME
medulla-scheduler-manager \- Launch Medulla2 scheduler manager
.SH SYNOPSIS
.B medulla-scheduler-manager
.RI [ options ] " command"
.SH DESCRIPTION
medulla-scheduler-manager is a tool of Medulla2. The « Scheduler » service is the Medulla 2 daemon in charge of reading the MSC database, dispatching commands over available launchers and writing results in the MSC database.
.TP
The goal is to provide a helper to run scheduler:
 * start (fork)
 * stop (kill)
.SH OPTIONS
.TP
.B \-h, \-\-help
Show the internal help message and exit
.TP
.B \-c CONFIG_FILE, \-\-config-file=CONFIG_FILE
Path to the config file
.TP
.B \-o ID, \-\-id=ID
ID of this scheduler
.SH COMMANDS
.B start
.TP
.B restart
.TP
.B stop
.TP
.B graceful-restart
.TP
.B graceful-stop
.SH AUTHOR
Medulla2 was written by Mandriva-Linbox
.SH COPYRIGHT
.TP
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
.TP
(c) 2007-2008 Mandriva, http://www.mandriva.com
.TP
Medulla2 is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH SEE ALSO
.BR medulla-scheduler (1).
