.TH PULSE2-LAUNCHER 1
.SH NAME
pulse2-launcher \- Launch Pulse2 launcher service
.SH SYNOPSIS
.B pulse2-launcher
.RI [ options ]
.SH DESCRIPTION
pulse2-launcher is a tool of Pulse2. The « Launcher » service is the Pulse 2 daemon in charge of doing jobs on clients on scheduler orders.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show the internal help message and exit
.TP
.B \-c CONFIG_FILE, \-\-config-file=CONFIG_FILE
Path to the config file
.TP
.B \-i ID, \-\-id=ID
Id of this launcher
.TP
.B \-l LOG_CONFIG_FILE, \-\-log-config-file=LOG_CONFIG_FILE
Path to the logging config file
.SH AUTHOR
Pulse2 was written by Mandriva-Linbox
.SH COPYRIGHT
.TP
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
.TP
(c) 2007-2008 Mandriva, http://www.mandriva.com
.TP
Pulse2 is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH SEE ALSO
.BR pulse2-launchers-manager (1).
