.TH PULSE2-PING 1
.SH NAME
pulse2-ping \- Launch a ping to the target given
.SH SYNOPSIS
.B pulse2-ping
.RI " "target
.SH DESCRIPTION
pulse2-ping is a tool of Pulse2. It allows to ping the
.I target
server.
.SH AUTHOR
Pulse2 was written by Mandriva-Linbox
.SH COPYRIGHT
.TP
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
.TP
(c) 2007-2008 Mandriva, http://www.mandriva.com
.TP
Pulse2 is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
