.TH PULSE2-PACKAGE-SERVER 1
.SH NAME
pulse2-package-server \- Launch Pulse 2 Package Server daemon 
.SH SYNOPSIS
.B pulse2-package-server
.RI [ options ]
.SH DESCRIPTION
pulse2-package-server is a tool of Pulse2. Launch Pulse 2 Package Server daemon.
.SH OPTIONS
.TP
.B \-f FILE
Alternate configuration file
.TP
.B \-d
Launch in debug mode
.SH AUTHOR
Pulse2 was written by Mandriva-Linbox
.SH COPYRIGHT
.TP
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
.TP
(c) 2007-2008 Mandriva, http://www.mandriva.com
.TP
Pulse2 is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH SEE ALSO
.BR pulse2-package-server-register-imaging (1).
