.TH PULSE2-PACKAGE-SERVER-REGISTER-IMAGING 1
.SH NAME
pulse2-package-server-register-imaging \- Pulse 2 Package Server Imaging module registration.
.SH SYNOPSIS
.B pulse2-package-server-register-imaging
.RI [ options ]
.SH DESCRIPTION
pulse2-package-server-register-imaging is a tool of Pulse2. This is for Pulse 2 Package Server Imaging module registration.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show the internal help message and exit
.TP
.B \-m|\-\-mmc\-agent\-url http://...
MMC Agent URL (mandatory)
.TP
.B \-n|\-\-name 'My Imaging Server'
Imaging server name
.TP
.B \-c|\-\-certificates 'cacert:localcert'
Verify peer with those certs
.TP
.B \-i|\-\-inifile /path/to/file
Alternate configuration file
.TP
.B \-u|\-\-uuid
Generates an UUID
.TP
.B \-C|\-\-check
Check if UUID is already registered
.TP
.B \-q|\-\-quiet
Be quiet
.TP
.B \-V|\-\-verbose
Be more verbose
.SH AUTHOR
Pulse2 was written by Mandriva-Linbox
.SH COPYRIGHT
.TP
(c) 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
.TP
(c) 2007-2008 Mandriva, http://www.mandriva.com
.TP
Pulse2 is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH SEE ALSO
.BR pulse2-package-server (1).
