# -*- coding: utf-8; -*-
# SPDX-FileCopyrightText: 2004-2007 Linbox / Free&ALter Soft, http://linbox.com
# SPDX-FileCopyrightText: 2007-2010 Mandriva, http://www.mandriva.com/
# SPDX-FileCopyrightText: 2016-2023 Siveo <support@siveo.net> 
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Contains constants for the audit system.
"""

class AuditActions:
    BASE_ADD_USER = u'BASE_ADD_USER'
    BASE_ENABLE_USER = u'BASE_ENABLE_USER'
    BASE_DISABLE_USER = u'BASE_DISABLE_USER'
    BASE_MOD_USER_ATTR = u'BASE_MOD_USER_ATTR'
    BASE_MOD_GROUP = u'BASE_MOD_GROUP_ATTR'
    BASE_ADD_GROUP = u'BASE_ADD_GROUP'
    BASE_ADD_USER_TO_GROUP = u'BASE_ADD_USER_TO_GROUP'
    BASE_DEL_USER_FROM_GROUP = u'BASE_DEL_USER_FROM_GROUP'
    BASE_DEL_USER_FROM_ALL_GROUPS = u'BASE_DEL_USER_FROM_ALL_GROUPS'
    BASE_MOD_USER_PGROUP = u'BASE_MOD_USER_PGROUP'
    BASE_DEL_USER = u'BASE_DEL_USER'
    BASE_DEL_USER_ATTR = u'BASE_DEL_USER_ATTR'
    BASE_MOD_USER_PASSWORD = u'BASE_MOD_USER_PASSWORD'
    BASE_DEL_GROUP = u'BASE_DEL_GROUP'
    BASE_BACKUP_USER = u'BASE_BACKUP_USER'
    BASE_AUTH_USER = u'BASE_AUTH_USER'
    BASE_MOVE_USER_HOME = u'BASE_MOVE_USER_HOME'
    BASE_ADD_OU = u'BASE_ADD_OU'
AA = AuditActions

class AuditTypes:
    USER = u'USER'
    GROUP = u'GROUP'
    ATTRIBUTE = u'ATTRIBUTE'
    ORGANIZATIONAL_UNIT = u'ORGANIZATIONAL_UNIT'
AT = AuditTypes

PLUGIN_NAME = u'MMC-BASE'
