#!/bin/bash
#
# Script to rebuild the ether file
#

DIR=/tftpboot/revoboot/images

pushd $DIR > /dev/null

num=0
for mac in [0-9A-F]*
do	
	for i in 0 2 4 6 8 10
	do
		echo -n ${mac:$i:2}
		if [ $i != 10 ]
		then
			echo -n :
		else
			if [ -e "$mac/hostname" ]
			then
				echo " Dynamic "`cat "$mac/hostname"`
			else
				echo " Dynamic Unknown$num"
				num=`expr $num + 1`
			fi
		fi
	done
done

popd > /dev/null

exit 0
