#!/usr/bin/perl
#
# Script to rotate LRS client logs
#
# $Id: rotatelog 4052 2007-02-21 11:25:26Z root $
#
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.


my $log = $ARGV[0];
my $lines = 30;

if ($ARGV[0] eq "") {
    print ("Usage: rotatelog PATH/log\n");
    exit;
}

rename($log, $log.".bak");
# keep only the last lines of the log
system("tail -$lines < $log.bak > $log");
exit 0;
