#
# $Id$
#

CFLAGS=-O2 -Wall
CFLAGS=-Wall -g

pulse2-imaging-server: dictionary.c iniparser.c pulse2-imaging-server.c strlib.c

pulse2-imaging-server.c: pulse2-imaging-server.h

clean:
	$(RM) pulse2-imaging-server
