#!/bin/sh
set -e
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  pulse2-scheduler.public
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/pulse2-scheduler" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d pulse2-scheduler stop || true
	else
		/etc/init.d/pulse2-scheduler stop || true
	fi
fi
# End automatically added section
