usr/share/doc/pulse2/* usr/share/doc/pulse2-common
usr/share/mmc/conf/apache/pulse.conf
etc/apache2/conf-available/pulse.conf
usr/share/doc/mmc
usr/sbin/pulse2-setup
usr/sbin/pulse2-create-group
usr/sbin/pulse2-load-defaults
usr/sbin/pulse2-create-group
usr/sbin/restart-pulse-services
usr/sbin/pulse2-debug
usr/sbin/pulse2-dbupdate
usr/sbin/pulse2-collect-info
usr/sbin/pulse-packageparser.py
var/lib/pulse2/file-transfer
