#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd | grep -q "^medullatransfert:"; then
            echo -n "Adding user medullatransfert..."
            adduser --system --quiet \
                    --home /var/lib/medulla/file-transfer \
                    --shell /bin/rbash \
                    --disabled-password \
                    medullatransfert
            echo "..done"
        fi
        ;;
esac

#DEBHELPER#

exit 0
~                                       
