#!/bin/sh
set -e

case "$1" in
    configure)
        if getent passwd www-data >/dev/null 2>&1; then
            chown www-data:root /etc/mmc/plugins/support || true
        fi
        chmod 750 /etc/mmc/plugins/support
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
