Pulse: WUInjectDB Class Reference
WUInjectDB Class Reference
Public Member Functions
def cursor (self)
def insert_target (self, update_id, uuid, is_installed)
def update_target (self, update_id, uuid, is_installed)
def purge_obselete_updates (self, uuid, update_uuids)
def insert_WU (self, uuid, title, kb_number, type_id, need_reboot, request_user_input, os_class_id, info_url)
def inject (self, target_uuid, uuid, title, kb_number, type_id, need_reboot, request_user_input, os_class_id, info_url, is_installed)
Detailed Description
A shortcut to insert the Windows Updates into the 'update' database.
Definition at line 238 of file utils.py.
Member Function Documentation
def cursor (self)
@return: dataset cursor
@rtype: object
Definition at line 266 of file utils.py.
References WUInjectDB.cursor().
Referenced by WUInjectDB.cursor(), WUInjectDB.insert_target(), WUInjectDB.insert_WU(), WUInjectDB.purge_obselete_updates(), and WUInjectDB.update_target().
def inject (self, target_uuid, uuid, title, kb_number, type_id, need_reboot, request_user_input, os_class_id, info_url, is_installed)
Injects the parsed stdout content into 'update' database.
Definition at line 436 of file utils.py.
References WUInjectDB.get_update_id(), WUInjectDB.insert_target(), WUInjectDB.insert_WU(), WUInjectDB.target_exists(), WUInjectDB.update_target(), and WUInjectDB.uuid_exists().
Referenced by WUInjectDB.insert_WU().
def insert_target (self, update_id, uuid, is_installed)
Inserts the target with a update reference.
Definition at line 309 of file utils.py.
References WUInjectDB.cursor().
Referenced by WUInjectDB.inject().
def insert_WU (self, uuid, title, kb_number, type_id, need_reboot, request_user_input, os_class_id, info_url)
Windows Updates insert
Definition at line 380 of file utils.py.
References WUInjectDB.cursor(), and WUInjectDB.inject().
Referenced by WUInjectDB.inject(), and WUInjectDB.purge_obselete_updates().
def purge_obselete_updates (self, uuid, update_uuids)
Purge all target links if update are no more present
in json
Definition at line 344 of file utils.py.
References WUInjectDB.cursor(), and WUInjectDB.insert_WU().
def update_target (self, update_id, uuid, is_installed)
Update the target with a update reference.
Definition at line 327 of file utils.py.
References WUInjectDB.cursor().
Referenced by WUInjectDB.inject().
The documentation for this class was generated from the following file:
services/pulse2/scheduler/utils.py