Pulse: StatisticsProcessing Class Reference
StatisticsProcessing Class Reference
Public Member Functions
def update (self, cmd_id=None)
def check_and_schedule_for_expired (self)
def watchdog_schedule (self, cmd_id)
Detailed Description
Provides the periodical and final updates of global command statistics.
Statistics are periodically updated to have a global sumarization
of states of commands on host.
Final statistics update is called on the last switching a circuit
to overtimed state. This update is scheduled with a delay having
the possibility to cancel if the previous updated circuit wasn't
the last definitive circuit of updated command.
Definition at line 31 of file stats.py.
Member Function Documentation
def check_and_schedule_for_expired (self)
Looks for expired commands and schedules an update
Definition at line 65 of file stats.py.
References StatisticsProcessing._get_stats(), StatisticsProcessing.previous, StatisticsProcessing.stats, StatisticsProcessing.watchdog_schedule(), and StatisticsProcessing.wdogs.
Referenced by StatisticsProcessing.update().
def update (self, cmd_id = None)
Updates the global statistics or just for one command
Definition at line 56 of file stats.py.
References StatisticsProcessing._get_stats(), StatisticsProcessing.check_and_schedule_for_expired(), and StatisticsProcessing.stats.
def watchdog_schedule (self, cmd_id)
Schedules the final stats update.
@param cmd_id: id of Commands record
@type cmd_id: int
Definition at line 123 of file stats.py.
References StatisticsProcessing._update_for(), and StatisticsProcessing.wdogs.
Referenced by StatisticsProcessing.check_and_schedule_for_expired().
The documentation for this class was generated from the following file:
services/pulse2/scheduler/stats.py