Pulse: DownloadAppstreamPackageList Class Reference
DownloadAppstreamPackageList Class Reference
Inherits object.
Public Member Functions
def getDownloadAppstreamPackages (self)
def updateAppstreamPackages (self)
Detailed Description
Create list of Appstream who need to be download and download them
Definition at line 297 of file __init__.py.
Member Function Documentation
def getDownloadAppstreamPackages (self)
This methods return dict of packages who need
to be download
@rtype: dict of unicode like { 'package_name' : 'status' } ,
    valid status are "download" and "wait".
@return: list of new appstream packages name who are not
yet downloaded.
Definition at line 331 of file __init__.py.
References DownloadAppstreamPackageList.download_packages.
Referenced by DownloadAppstreamPackageList.updateAppstreamPackages().
def updateAppstreamPackages (self)
This methode update appstream package and download package who need to be
download. It can effectly work only one at a time.
@rtype: bool
@return: True if done,False if already working.
Definition at line 342 of file __init__.py.
References DownloadAppstreamPackageList._add_appstream(), DownloadAppstreamPackageList._finish_appstream(), DownloadAppstreamPackageList._start_appstream(), DownloadAppstreamPackageList.getDownloadAppstreamPackages(), and DownloadAppstreamPackageList.update.
The documentation for this class was generated from the following file:
services/mmc/plugins/pkgs/__init__.py