Pulse: PieChart Class Reference
PieChart Class Reference
Public Member Functions
PieChart ($width=600, $height=250)
render ($fileName=null)
Public Member Functions inherited from Chart
setDataSet ($dataSet)
getConfig ()
getPlot ()
setTitle ($title)
Protected Member Functions
computeLayout ()
sortPie ($v1, $v2)
computePercent ()
createImage ()
printCaption ()
drawDisc ($cy, $colorArray, $mode)
drawPercent ()
printPie ()
Protected Member Functions inherited from Chart
Chart ($width, $height)
checkDataModel ()
createImage ()
Additional Inherited Members
Protected Attributes inherited from Chart
$config
$dataSet
$plot
Detailed Description
Pie chart.
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com)
Definition at line 25 of file PieChart.php.
Member Function Documentation
computeLayout () protected
Computes the layout.
Definition at line 43 of file PieChart.php.
Referenced by render().
computePercent () protected
Compute pie values in percentage and sort them.
Definition at line 75 of file PieChart.php.
Referenced by render().
createImage () protected
Creates the pie chart image.
Definition at line 99 of file PieChart.php.
Referenced by render().
drawDisc ($cy, $colorArray, $mode) protected
Draw a 2D disc.
Parameters
integer Center coordinate (y)
array Colors for each portion
bitfield Drawing mode
Definition at line 153 of file PieChart.php.
Referenced by printPie().
drawPercent () protected
Print the percentage text.
Definition at line 188 of file PieChart.php.
Referenced by printPie().
PieChart ($width = 600, $height = 250)
Constructor of a pie chart.
Parameters
integer width of the image
integer height of the image
Definition at line 35 of file PieChart.php.
printCaption () protected
Renders the caption.
Definition at line 123 of file PieChart.php.
Referenced by render().
printPie () protected
Print the pie chart.
Definition at line 224 of file PieChart.php.
References drawDisc(), and drawPercent().
Referenced by render().
render ($fileName = null)
Render the chart image.
Parameters
string name of the file to render the image to (optional)
Definition at line 254 of file PieChart.php.
References computeLayout(), computePercent(), createImage(), printCaption(), and printPie().
sortPie ($v1, $v2) protected
Compare two sampling point values, order from biggest to lowest value.
Parameters
double first value
double second value
Returns
integer result of the comparison
Definition at line 66 of file PieChart.php.
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/chart/PieChart.php