Pulse: BarChart Class Reference
BarChart Class Reference
Public Member Functions
getBound ()
Public Member Functions inherited from Chart
setDataSet ($dataSet)
getConfig ()
getPlot ()
setTitle ($title)
Protected Member Functions
BarChart ($width, $height)
computeAxis ()
createImage ()
isEmptyDataSet ($minNumberOfPoint)
checkDataModel ()
getDataAsSerieList ()
getFirstSerieOfList ()
Protected Member Functions inherited from Chart
Chart ($width, $height)
checkDataModel ()
createImage ()
Additional Inherited Members
Protected Attributes inherited from Chart
$config
$dataSet
$plot
Detailed Description
Base abstract class for rendering both horizontal and vertical bar charts.
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com)
Definition at line 25 of file BarChart.php.
Member Function Documentation
BarChart ($width, $height) protected
Creates a new bar chart.
Parameters
integer width of the image
integer height of the image
Definition at line 36 of file BarChart.php.
checkDataModel () protected
Checks the data model before rendering the graph.
Definition at line 106 of file BarChart.php.
Referenced by LineChart\render(), VerticalBarChart\render(), and HorizontalBarChart\render().
computeAxis () protected
Compute the axis.
Definition at line 47 of file BarChart.php.
References Axis\computeBoundaries().
Referenced by LineChart\render(), VerticalBarChart\render(), and HorizontalBarChart\render().
createImage () protected
Create the image.
Definition at line 55 of file BarChart.php.
Referenced by LineChart\render(), VerticalBarChart\render(), and HorizontalBarChart\render().
getBound ()
Retourns the bound.
Returns
bound Bound
Definition at line 179 of file BarChart.php.
getDataAsSerieList () protected
Return the data as a series list (for consistency).
Returns
List of series
Definition at line 141 of file BarChart.php.
Referenced by VerticalBarChart\printBar(), HorizontalBarChart\printBar(), and LineChart\printLine().
getFirstSerieOfList () protected
Return the first serie of the list, or the dataSet itself if there is no serie.
Returns
XYDataSet
Definition at line 159 of file BarChart.php.
Referenced by LineChart\printAxis(), VerticalBarChart\printAxis(), and HorizontalBarChart\printAxis().
isEmptyDataSet ($minNumberOfPoint) protected
Returns true if the data set has some data.
Parameters
minNumberOfPoint Minimum number of points (1 for bars, 2 for lines).
Returns
true if data set empty
Definition at line 84 of file BarChart.php.
Referenced by LineChart\render(), VerticalBarChart\render(), and HorizontalBarChart\render().
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/chart/BarChart.php