Pulse: Palette Class Reference
Palette Class Reference
Public Member Functions
Palette ()
setAxisColor ($colors)
setBackgroundColor ($colors)
setBarColor ($colors)
setLineColor ($colors)
setPieColor ($colors)
Detailed Description
Color palette shared by all chart types.
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com) Created on 25 july 2007
Definition at line 26 of file Palette.php.
Member Function Documentation
Palette ()
Palette constructor.
Definition at line 40 of file Palette.php.
References setAxisColor(), setBackgroundColor(), setBarColor(), setLineColor(), and setPieColor().
setAxisColor ($colors)
Set the colors for the axis.
Parameters
colors Array of Color
Definition at line 116 of file Palette.php.
Referenced by Palette().
setBackgroundColor ($colors)
Set the colors for the background.
Parameters
colors Array of Color
Definition at line 125 of file Palette.php.
Referenced by Palette().
setBarColor ($colors)
Set the colors for the bar charts.
Parameters
colors Array of Color
Definition at line 134 of file Palette.php.
Referenced by Palette().
setLineColor ($colors)
Set the colors for the line charts.
Parameters
colors Array of Color
Definition at line 143 of file Palette.php.
Referenced by Palette().
setPieColor ($colors)
Set the colors for the pie charts.
Parameters
colors Array of Color
Definition at line 152 of file Palette.php.
Referenced by Palette().
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/color/Palette.php