Pulse: LicenseChecker Class Reference
LicenseChecker Class Reference
Inherits object.
Public Member Functions
def get_license_info (self, offline=False)
def data_extract (self, response)
def normalize (self, data)
def eb_get_info (self, failure)
def update_panel (self, data)
Detailed Description
Periodical checks to license server.
This checks are triggered by cron and returned and parsed data
updates the license widget on dashboard.
Definition at line 60 of file __init__.py.
Member Function Documentation
def data_extract (self, response)
Custom corrections to display the license info.
@param data: decoded data returned from license server
@type data: list
@return: transformed data
@rtype: dict
Definition at line 101 of file __init__.py.
References LicenseChecker.normalize().
Referenced by LicenseChecker.get_license_info().
def eb_get_info (self, failure)
Common errorback for querying and parsing
Definition at line 209 of file __init__.py.
Referenced by LicenseChecker.get_license_info().
def get_license_info (self, offline = False)
Checks the license info on license server.
@param offline: temp file check only
@type offline: bool
@return: True when successfull query and data parse
@rtype: Deferred
Definition at line 70 of file __init__.py.
References LicenseChecker.data_extract(), LicenseChecker.eb_get_info(), and LicenseChecker.update_panel().
def normalize (self, data)
Converts all elements with unicode escape characters to unicode chars.
Includes also nested lists containing another dicts.
@param data: extracted response from the license server
@type data: dict
@return: converted data
@rtype: dict
Definition at line 186 of file __init__.py.
References LicenseChecker.normalize().
Referenced by LicenseChecker.data_extract(), and LicenseChecker.normalize().
def update_panel (self, data)
Updates the license widget for dashboard.
@param data: parsed data ready for widget display
@type data: dict
Definition at line 215 of file __init__.py.
Referenced by LicenseChecker.get_license_info().
The documentation for this class was generated from the following file:
services/mmc/plugins/support/__init__.py