Pulse: Color Class Reference
Color Class Reference
Public Member Functions
Color ($red, $green, $blue, $alpha=0)
getColor ($img)
clip ($component)
getShadowColor ($shadowFactor)
Detailed Description
Color.
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com)
Definition at line 25 of file Color.php.
Member Function Documentation
clip ($component)
Clip a color component in the interval [0..255]
Parameters
integer Component
Returns
Clipped component
Definition at line 74 of file Color.php.
Referenced by getShadowColor().
Color ($red, $green, $blue, $alpha = 0)
Creates a new color
Parameters
integer red [0..255]
integer green [0..255]
integer blue [0..255]
integer alpha [0..255]
Definition at line 40 of file Color.php.
Referenced by getShadowColor().
getColor ($img)
Get GD color.
Parameters
$img GD image resource
Definition at line 54 of file Color.php.
getShadowColor ($shadowFactor)
Return a new color, which is a shadow of this one.
Parameters
double Multiplication factor
Returns
Shadow color
Definition at line 90 of file Color.php.
References clip(), and Color().
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/color/Color.php