Pulse: Collector Class Reference
Collector Class Reference
Inherits object.
Public Member Functions
def queue_and_process (self, ip, request)
def get (self)
def release (self, uid, result)
Detailed Description
Provides a smart buffer of request.
Because some requests can be long and heavy, this provider
allows to put the requests into a queue where other side may
treat previous requests until last added.
During making of each request, an identifier and a new deferred
is created. This deferred is assigned to incomming session
of request which is waiting with its unfired deffered.
When queued request is processed and a result is returned,
waiting related deferred is fired with this result.
Definition at line 234 of file collector.py.
Member Function Documentation
def get (self)
Returns uid and request data as PacketRef object.
This method should be called by a service processing requests
to get a request specification. This request is released from
internal queue, but its deferred still stored in session tracker.
@return: uuid and request
@rtype: deferred
Definition at line 274 of file collector.py.
References Collector.sessions.
Referenced by RPCStore.add(), RPCStore.check(), BundleReferences.clean_up(), RPCStore.debug(), RPCStore.discardRPCs(), BundleReferences.finish(), BundleReferences.get_next_in_order(), ExtendedConfigParser.getlist(), Pulse2ConfigParser.getpassword(), RPCStore.init(), BundleReferences.is_previous_finished(), Circuit.phase_step(), RPCStore.pop(), ImagingConfig.readConf(), Refresh.refresh(), MscDispatcher.release(), BundleReferences.remove_bundle(), MscDispatcher.remove_expired(), MethodProxy.run_proxymethod(), MscDispatcher.start_all(), and BundleReferences.update().
def queue_and_process (self, ip, request)
Inserts request into the queue.
Each queued request returns a deferred which will be fired
when a queued element is processed.
@param request
Definition at line 259 of file collector.py.
def release (self, uid, result)
Releases queued request and fires related deferred.
@param uid: session identifier
@type uid: int
@param result: reason of fired deferred
@type result: any
@return: fired deferred - can be useful to chain another action
@rtype: Deferred
Definition at line 296 of file collector.py.
Referenced by Circuit.phase_process(), Circuit.phase_step(), and Circuit.run().
The documentation for this class was generated from the following file:
services/pulse2/cm/collector.py