Pulse: NetUtils Class Reference
NetUtils Class Reference
Public Member Functions
def get_netmask (cls)
def on_same_network (cls, ip, network, netmask)
def check_netmask (cls, network, netmask)
def netmask_to_cidr (cls, netmask)
def has_enough_info (cls, iface)
def is_ipv4_format (cls, candidate)
def netmask_validate (cls, netmask)
def ipv4_to_dec (cls, address)
def is_port_free (cls, port, host="127.0.0.1")
Detailed Description
Common network utils
Definition at line 40 of file network.py.
Member Function Documentation
def check_netmask (cls, network, netmask)
Test if defined netmask of network is correct.
@param network: address of network
@type network: string
@param netmask: netmask of network
@type netmask: string
@return: True if IP address are in the same network.
@rtype: bool
Definition at line 90 of file network.py.
References NetUtils.netmask_to_cidr().
Referenced by NetUtils.on_same_network().
def get_netmask (cls)
Getting the server's netmask
@return: netmask
@rtype: str
Definition at line 44 of file network.py.
def has_enough_info (cls, iface)
Test if interface has enough informations for resolving methods.
@param iface: networking parameters of interface
@type iface: dict
@return: True if enough info
@rtype: bool
Definition at line 136 of file network.py.
def ipv4_to_dec (cls, address)
Converts a IPv4 address string to list of integers.
i.e. '192.168.12.206' --> [192, 168, 12, 206]
@param address: address to extract
@type address: string
@return: ip address in list of integers
@rtype: list
Definition at line 194 of file network.py.
def is_ipv4_format (cls, candidate)
Validating the IPv4 address format.
@param candidate: candidate string to validate
@str candidate: str
@return: True if correct IPv4 format
@rtype: bool
Definition at line 155 of file network.py.
def is_port_free (cls, port, host = "127.0.0.1")
Check if port on host is free.
@param port: checked port
@type port: int
@param host: checked host
@type host: str
@return: True if port is free
@rtype: bool
Definition at line 209 of file network.py.
def netmask_to_cidr (cls, netmask)
Converting decimal dotted subnet mask to CIDR format
i.e.: 255.255.255.0 -> 24
@param netmask: netmask on dotted decimal format
@type netmask: str
@return: number of bits (CIDR)
@rtype: int
Definition at line 111 of file network.py.
Referenced by NetUtils.check_netmask(), and NetUtils.on_same_network().
def netmask_validate (cls, netmask)
Check of netmask format
@param netmask: checked netmask
@type netmask: str
@return: True if netmask is valid
@rtype: bool
Definition at line 174 of file network.py.
def on_same_network (cls, ip, network, netmask)
Test if IP address can be found in network.
@param ip: tested IP adddress
@type ip: string
@param network: address of network
@type network: string
@param netmask: netmask of network
@type netmask: string
@return: True if IP address are in the same network.
@rtype: bool
Definition at line 61 of file network.py.
References NetUtils.check_netmask(), and NetUtils.netmask_to_cidr().
The documentation for this class was generated from the following file:
services/pulse2/network.py