Pulse: updateDatabase Class Reference
updateDatabase Class Reference
Inherits DatabaseHelper.
Public Member Functions
def initMappers (self)
def get_os_classes (self, session, params)
def enable_only_os_classes (self, session, os_classes_ids)
def get_update_types (self, session, params)
def set_update_type_status (self, session, update_type_id, status)
def push_updates (self, session, uuid, updates)
def get_updates (self, session, params)
def set_update_status (self, session, update_id, status)
def get_updates_for_host_by_dominant_status (self, session, uuid, dStatus, is_installed=None)
def printquery (self, statement, bind=None)
def get_eligible_updates_for_host (self, session, uuid)
def get_disabled_updates_for_host (self, session, uuid)
def get_neutral_updates_for_host (self, session, uuid)
def set_update_status_for_hosts (self, session, uuid, update_id, status)
Detailed Description
Singleton Class to query the update database.
Definition at line 35 of file database.py.
Member Function Documentation
def enable_only_os_classes (self, session, os_classes_ids)
Enable spacified os_classes and disble others
Definition at line 82 of file database.py.
def get_disabled_updates_for_host (self, session, uuid)
Get all update to install for host,
this function return all eligible updates for the host
in this order of priority: Target -> Update -> Update Type
Definition at line 337 of file database.py.
References updateDatabase.get_updates_for_host_by_dominant_status().
def get_eligible_updates_for_host (self, session, uuid)
Get all update to install for host,
this function return all eligible updates for the host
in this order of priority: Target -> Update -> Update Type
Definition at line 327 of file database.py.
References updateDatabase.get_updates_for_host_by_dominant_status().
def get_neutral_updates_for_host (self, session, uuid)
Get all update to install for host,
this function return all neutral updates for the host
in this order of priority: Target -> Update -> Update Type
Definition at line 347 of file database.py.
def get_os_classes (self, session, params)
Get all os classes
Definition at line 74 of file database.py.
def get_update_types (self, session, params)
Get all update types
Definition at line 103 of file database.py.
def get_updates (self, session, params)
Get all updates by the specified filters
Status filter is specially treaten
in this order of priority: Update -> Update Type
Definition at line 167 of file database.py.
def get_updates_for_host_by_dominant_status (self, session, uuid, dStatus, is_installed = None)
Get all update to install for host,
this function return all updates for the host
if the update have the Status (STATUS_ENABLED or STATUS_DISABLED, STATUS_NEUTRAL)
in this order of priority:
Target -> Update -> Update Type
Definition at line 240 of file database.py.
Referenced by updateDatabase.get_disabled_updates_for_host(), and updateDatabase.get_eligible_updates_for_host().
def initMappers (self)
This Method is nomore need, all tables are mapped on schema.py
Definition at line 62 of file database.py.
def printquery (self, statement, bind = None)
print a query, with values filled in
for debugging purposes *only*
for security, you should always separate queries from their values
please also note that this function is quite slow
Definition at line 294 of file database.py.
def push_updates (self, session, uuid, updates)
This function Adds updates in updates table
and link them to the specified uuid
updates: list of {
    name: , guid : , os_class_id , type_id , status [optional]
}
Definition at line 129 of file database.py.
def set_update_status (self, session, update_id, status)
Set the global update status
Definition at line 220 of file database.py.
def set_update_status_for_hosts (self, session, uuid, update_id, status)
Set the update status for the target host only
(global update status will remain unchanged)
Definition at line 378 of file database.py.
def set_update_type_status (self, session, update_type_id, status)
Set the update type status
Definition at line 111 of file database.py.
The documentation for this class was generated from the following file:
services/mmc/plugins/update/database.py