Pulse: Axis Class Reference
Axis Class Reference
Public Member Functions
Axis ($min, $max)
quantizeTics ()
computeBoundaries ()
getLowerBoundary ()
getUpperBoundary ()
getTics ()
Detailed Description
Automatic axis boundaries and ticks calibration
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com)
Definition at line 25 of file Axis.php.
Member Function Documentation
Axis ($min, $max)
Creates a new axis formatter.
Parameters
integer minimum value on the axis
integer maximum value on the axis
Definition at line 41 of file Axis.php.
computeBoundaries ()
Computes automatic boundaries on the axis
Definition at line 80 of file Axis.php.
References quantizeTics().
Referenced by BarChart\computeAxis().
getLowerBoundary ()
Get the lower boundary on the axis3
Returns
integer lower boundary on the axis
Definition at line 108 of file Axis.php.
getTics ()
Get the value between two ticks3
Returns
integer value between two ticks
Definition at line 126 of file Axis.php.
getUpperBoundary ()
Get the upper boundary on the axis3
Returns
integer upper boundary on the axis
Definition at line 117 of file Axis.php.
quantizeTics ()
Computes value between two ticks.
Definition at line 51 of file Axis.php.
Referenced by computeBoundaries().
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/axis/Axis.php