Pulse: VerticalBarChart Class Reference
VerticalBarChart Class Reference
Public Member Functions
VerticalBarChart ($width=600, $height=250)
render ($fileName=null)
Public Member Functions inherited from BarChart
getBound ()
Public Member Functions inherited from Chart
setDataSet ($dataSet)
getConfig ()
getPlot ()
setTitle ($title)
Protected Member Functions
computeLayout ()
printAxis ()
printBar ()
printCaption ()
Protected Member Functions inherited from BarChart
BarChart ($width, $height)
computeAxis ()
createImage ()
isEmptyDataSet ($minNumberOfPoint)
checkDataModel ()
getDataAsSerieList ()
getFirstSerieOfList ()
Protected Member Functions inherited from Chart
Chart ($width, $height)
checkDataModel ()
createImage ()
Additional Inherited Members
Protected Attributes inherited from Chart
$config
$dataSet
$plot
Detailed Description
Chart composed of vertical bars.
Author
Jean-Marc Trémeaux (jm.tremeaux at gmail.com)
Definition at line 25 of file VerticalBarChart.php.
Member Function Documentation
computeLayout () protected
Computes the layout.
Definition at line 47 of file VerticalBarChart.php.
Referenced by render().
printAxis () protected
Print the horizontal and veritcal axis.
Definition at line 57 of file VerticalBarChart.php.
References BarChart\getFirstSerieOfList().
Referenced by render().
printBar () protected
Print the bars.
Definition at line 107 of file VerticalBarChart.php.
References BarChart\getDataAsSerieList().
Referenced by render().
printCaption () protected
Renders the caption.
Definition at line 186 of file VerticalBarChart.php.
Referenced by render().
render ($fileName = null)
Render the chart image.
Parameters
string name of the file to render the image to (optional)
Definition at line 208 of file VerticalBarChart.php.
References BarChart\checkDataModel(), BarChart\computeAxis(), computeLayout(), BarChart\createImage(), BarChart\isEmptyDataSet(), printAxis(), printBar(), and printCaption().
VerticalBarChart ($width = 600, $height = 250)
Creates a new vertical bar chart
Parameters
integer width of the image
integer height of the image
Definition at line 37 of file VerticalBarChart.php.
The documentation for this class was generated from the following file:
web/modules/inventory/includes/libchart/classes/view/chart/VerticalBarChart.php