Pulse: ParabolicBalance Class Reference
ParabolicBalance Class Reference
Inherits object.
Public Member Functions
def __init__ (self, attempts_total)
def get_index (self, n)
def fx (self, x)
def fx_delta (self, x)
Detailed Description
A interpretation of run of the parabolic curve, based
on quadratic function : y = - ax^2 + bx.
The balance coeficient is based on matematical integration
of area between the parabolic curve and x-axis.
Output is a list of balance coeficients which total is 1.
Definition at line 30 of file balance.py.
Constructor & Destructor Documentation
def __init__ (self, attempts_total)
@param attempts_total: number of balances to calculate
@type attempts_total: int
Definition at line 60 of file balance.py.
References ParabolicBalance._balances, ParabolicBalance._calc(), and ParabolicBalance.attempts_total.
Member Function Documentation
def fx (self, x)
Integral of quadratic function.
ITG (-x^2 + kx) dx = - x^3/3 + 2kx/2
Definition at line 76 of file balance.py.
References ParabolicBalance.attempts_total.
Referenced by ParabolicBalance.fx_delta().
def fx_delta (self, x)
Get slice of integrated area.
Definition at line 85 of file balance.py.
References ParabolicBalance._balances, ParabolicBalance.attempts_total, ParabolicBalance.delta, ParabolicBalance.fx(), ParabolicBalance.fx_delta(), and ParabolicBalance.get_index().
Referenced by ParabolicBalance.fx_delta().
def get_index (self, n)
Definition at line 69 of file balance.py.
References ParabolicBalance.attempts_total, and ParabolicBalance.delta.
Referenced by ParabolicBalance.fx_delta().
The documentation for this class was generated from the following file:
services/pulse2/scheduler/balance.py