Pulse: PXEMethodParser Class Reference
PXEMethodParser Class Reference
Public Member Functions
def register (self)
def get_method (self, packet)
def get_args (self, method)
Detailed Description
Extracting the methods and arguments from packet.
All methods declared and decorated with @assign decorator
are registered into methods dictionnary.
Argument of @assign decorator is identifying a decorated
method with a value of first byte of incoming packet
from PXE imaging client.
When a method is resolved, instance of ArgumentContainer
extract the arguments and returns all as a method object.
Definition at line 293 of file parser.py.
Member Function Documentation
def get_args (self, method)
Extract the names of arguments from method.
@param method: method to extract
@type method: func
@return: list of names of arguments
@rtype: list
Definition at line 364 of file parser.py.
Referenced by PXEMethodParser.get_method().
def get_method (self, packet)
Returns a method to execute.
@param packet: packet recieved from imaging client
@type packet: str
@return: method to execute
@rtype: func
Definition at line 332 of file parser.py.
References PXEMethodParser.get_args(), and PXEMethodParser.methods.
def register (self)
Registering of decorated methods into methods dictionnary.
Definition at line 317 of file parser.py.
References PXEMethodParser.register_only.
Referenced by PhaseBase.__init__().
The documentation for this class was generated from the following file:
services/pulse2/package_server/imaging/pxe/parser.py