--- Makefile	2004-08-18 21:48:07.000000000 +0200
+++ Makefile.lrs	2008-03-10 22:27:17.000000000 +0100
@@ -11,7 +11,7 @@
 OSSLLIB=$(OSSLPATH)/lib
 OSSLINC=$(OSSLPATH)/include
 
-CC=gcc
+CC=gcc-3.3
 CFLAGS= -DUSEOPENSSL -g -I. -I$(OSSLINC) -Wall
 
 # This is to link with whatever we have, SSL crypto lib we put in static
@@ -26,11 +26,14 @@
 /usr/local/libold/ld-2.0.5.so \
 /usr/local/usr/lib/libc.so /usr/local/libold/libc-2.0.5.so /usr/local/usr/lib/crtn.o 
 
-all: chntpw
+all: chntpw chntpw.static
 
 chntpw: chntpw.o ntreg.o
 	$(CC) $(CFLAGS) -o chntpw chntpw.o ntreg.o $(LIBS)
 
+chntpw.static: chntpw.o ntreg.o
+	$(CC) $(CFLAGS) -static -o chntpw.static chntpw.o ntreg.o $(LIBS)
+
 cpnt: cpnt.o
 	$(CC) $(CFLAGS) -o cpnt cpnt.o $(LIBS)
 
