#!/bin/sh
#
# (c) 2003-2007 Linbox, http://www.linbox.com/
# (c) 2008-2009 Mandriva, http://www.mandriva.com/
#
# $Id: check_add_host 4805 2009-11-20 15:42:17Z nrueff $
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2.  If not, see <http://www.gnu.org/licenses/>.

# --- GET BASEDIR

CONFIG_FILE="/etc/mmc/pulse2/imaging-server/imaging-server.ini"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "create_config: '$CONFIG_FILE': File not found" >&2
    exit 1
fi

BASEDIR=$(grep -i '^ *base_folder' "$CONFIG_FILE" | tr "=" " " | awk {'print $2;'})
SKELDIR=$(grep -i '^ *templates_folder' "$CONFIG_FILE" | tr "=" " " | awk {'print $2;'})
UPDATEMENU=$(grep -i '^ *menu_update_path' "$CONFIG_FILE" | tr "=" " " | awk {'print $2;'})

if [ ! -d "$BASEDIR" ]; then
    echo "create_config: '$BASEDIR': Not a directory" >&2
    exit 1
fi

if [ ! -d "$SKELDIR" ]; then
    echo "create_config: '$SKELDIR': Not a directory" >&2
    exit 1
fi

# --- CREATE DIR

mkdir -p "$BASEDIR/images/$1" || exit 1

# --- POPULATE DIR

cd "$BASEDIR/images/$1"
(cd "$SKELDIR" && tar --exclude=.svn -cf - .) | tar -xf -

# --- CREATE DEFAULT CONFIG FILE

"$UPDATEMENU" $1
