#!/usr/bin/perl -w
#
# (c) 2003-2007 Linbox, http://www.linbox.com/
# (c) 2008-2009 Mandriva, http://www.mandriva.com/
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

# consts
$BASEDIR = "/var/lib/pulse2/imaging";

use lib "/usr/share/pulse2/imaging/helpers";
require "lrs-legacy.pl";

$iam = `basename $0`;
chomp($iam);

#//////////////////////////////////////////////////////////////////////////////

# badExit($message,[...])
#
sub badExit {
    my $msg = join( " ", @_ );
    print STDERR "$iam: $msg\n";
    exit(1);
}

#//////////////////////////////////////////////////////////////////////////////

badExit("'$BASEDIR': LBS basedir not found") if ( not -d $BASEDIR );

# load header
$header = "$BASEDIR/images/$ARGV[0]/header.lst";
$newdef = $ARGV[1];

if ( $ARGV[0] eq "" ) {
    print("Usage: set_default MAC ENTRYNUMBER\n");
    exit;
}

badExit("'$header': LBS menu not found") if ( not -f $header );

%conf = ();
iniLoad( $header, \%conf );

# reset default entries
my $ii = 0;
foreach my $sec ( iniGetSections( \%conf ) ) {
    my $visu = iniGetVal( \%conf, $sec, "visu" );

    # only take into account visible entries
    if ( $visu eq "no" || $visu eq "" ) { next; }
    my $val = iniGetVal( \%conf, $sec, "def" );
    if ( $ii == $newdef ) {
        iniSetVal( \%conf, $sec, "def", "yes" );
    }
    else {
        iniSetVal( \%conf, $sec, "def", "no" );
    }
    $ii++;
}
iniSave( $header, \%conf );

