#!/usr/bin/perl
#
# $Id$
#
# Executed when the client boots
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

my $home;
my $dummy;
BEGIN
{
 open F,"/etc/lbs.conf";
 while (<F>)
 {
	chomp;
	(my $dummy,$home)=split /[ \t]*=[ \t]*/ if /^basedir[ \t]*=/i;
 } 
 close(F);
}

use lib $home."/bin/";
require "lbs-lib.pl";

$macfile=$ARGV[0];

#print "Updating : $home/cfg/$macfile\n";

#$config{"lbshome"}=$home;

updateEntry($home, $macfile) or lbsDieError();

# reset files permissions: allow the diskless Linux to write to these files
# and ensure backward compatibility
for $i ( "log.restore", "postinst.log", "progress.txt" ) {
    system("touch $home/images/$macfile/$i ; chown 65534 $home/images/$macfile/$i");
}
