#!/usr/bin/perl -w
#
# (c) 2003-2007 Linbox, http://www.linbox.com/
# (c) 2008-2009 Mandriva, http://www.mandriva.com/
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

# consts
$CFGDIR = "/var/lib/tftpboot/pulse2";

use lib "/usr/share/pulse2/imaging/helpers";
require "lrs-legacy.pl";

$macfile=$ARGV[0];

updateEntry($CFGDIR, $macfile) or lbsDieError();

# reset files permissions: allow the diskless Linux to write to these files
# and ensure backward compatibility
for $i ( "log.restore", "postinst.log", "progress.txt" ) {
    system("touch $CFGDIR/images/$macfile/$i ; chown 65534 $CFGDIR/images/$macfile/$i");
}
