#!/bin/sh
ln -sf ../../imgbase/Local-Disk ./Local-Disk
ln -sf ../../imgbase/Backup-B ./Backup-B
ln -sf ../../imgbase/Backup-L ./Backup-L
ln -sf ../../imgbase/Util-Mbr ./Util-Mbr
ln -sf ../../imgbase/Util-MemTest ./Util-MemTest
ln -sf ../../imgbase/Local-Floppy ./Local-Floppy
