#!/bin/sh
#
# $Id$
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# --- GET BASEDIR

LBSCONF="/etc/lbs.conf"

if [ ! -f "$LBSCONF" ]; then
	echo "$0: '$LBSCONF': File not found" >&2
	exit 1
fi

BASEDIR=$(grep -i '^ *basedir' "$LBSCONF"|tr "=" " "|awk {'print $2;'})

if [ ! -d "$BASEDIR" ]; then
	echo "$0: '$BASEDIR': Not a directory" >&2
	exit 1
fi

#### 

if [ -z $1 ];then
    echo "usage: $0 password <list.txt
    
where list.txt contains one line per host in the form 'MA:CA:DD:RE:SS Hostname' 
"
    exit 0
fi

while read A B
do
    $BASEDIR/bin/check_add_host $A "$B" $1
done
