#!/usr/bin/perl
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

my %machine_hw_ip=();
my %machine_hw_onoff=();
my $basedir;

sub load_ether
{
 my %old_stat=%machine_hw_onoff;

 %machine_hw_ip=();
 %machine_hw_onoff=();

 open F,$basedir."/etc/ether";
 while (<F>)
 {
  chomp;
  next if /^#/;
  next if /^$/;

  my ($hw,$ip,$name)=split;
  $machine_hw_ip{$hw}=$ip;
  if (exists $old_stat{$hw}) {$machine_hw_onoff{$hw}=$old_stat{$hw};}
  			else {$machine_hw_onoff{$hw}="?";}
 }
 close(F);
}

sub write_check
{
 open G,">".$basedir."/log/status";
 foreach $i (keys %machine_hw_ip)
  {
   print G "$i $machine_hw_onoff{$i}\n";
  }
 close(G);
}

sub ping
{
 foreach $i (keys %machine_hw_ip)
 {
  if (system("ping -n -c1 ".$machine_hw_ip{$i}." >/dev/null 2>&1")==0) {$machine_hw_onoff{$i}="+";
   									system("sleep 10");}
                                           else     {$machine_hw_onoff{$i}="-";}
  write_check();
 }
}

open(CFG,"/etc/lbs.conf") or die;
while (<CFG>)
{
 chomp;
 (my $i,$basedir)=split /[ \t]*=[ \t]*/ if /^basedir[ \t]*=/i;
}
close(CFG);

while (1==1)
{
 load_ether();
 ping();
}

