#!/usr/bin/perl
#
# Script to rename a LRS host
#
# $Id: rename_host 2307 2005-06-13 09:40:44Z root $
#
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# MAIN ////////////////////////////////////////////////////////////////////////

my $old=$ARGV[0];
my $new=$ARGV[1];

if ($ARGV[1] eq "") {
    print ("Usage: rename_host OLD NEW\n");
    exit;
}

open CFG,"/etc/lbs.conf" or die;
while (<CFG>)
{
 chomp;
 (my $i,$base)=split /[ \t]*=[ \t]*/ if /^basedir[ \t]*=/i;
}
close(CFG);

require "$base/bin/inifile.pl" ;
require "$base/bin/lbs-lib.pl" ;

my $eth=$base."/etc/ether";
my $log=$base."/log/addhost.log";

my %einfo;

etherLoad($eth, \%einfo) or die( "file open failed $eth") ;

# redirect to the good page
$mac = $in{'mac'};
$redir = "bootmenu.cgi?mac=$mac";

$mac = etherGetMacByName(\%einfo, $ARGV[0]) ;

if ( $mac eq "") {
    die("Cannot find host $ARGV[0]");
}


# now rename

$einfo{$mac}[1] = $ARGV[1] ;
etherSave($eth, \%einfo) ;

# update the hostname file
open(HOST,">$base/images/".toMacFileName($mac)."/hostname");
print HOST $ARGV[1];
close(HOST);
        
print ("Renamed !\n");
exit 0;
